version: "3.5"

services:
  api01: &api
    build: .
    container_name: api01
    volumes:
      - .:/app
    hostname: api01
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laraveio
      - DB_USERNAME=pedro
      - DB_PASSWORD=delara
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api 
    hostname: api02
    container_name: api02
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=delara
      - POSTGRES_USER=pedro
      - POSTGRES_DB=laraveio
    ports:
      - "5432:5432"
    volumes:
      - ./config/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "300MB"